development:
  adapter: mysql
  encoding: utf8
  database: ls2_development
  username: root
  password: root


test:
  adapter: mysql
  encoding: utf8
  database: ls_test
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

staging:
  adapter: mysql
  encoding: utf8
  database: ls_production
  username: root
  password: dvf27378
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: ls_production
  username: root
  password: dvf27378
  socket: /opt/local/var/run/mysql5/mysqld.sock
